name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v3  # Aggiornato alla versione 3

    - name: Set up Python
      uses: actions/setup-python@v4  # Aggiornato alla versione 4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip openjdk-8-jdk
        pip install buildozer

    - name: Initialize Buildozer
      run: buildozer android debug
      env:
        ANDROID_NDK_HOME: /opt/android/android-ndk
        ANDROID_SDK_ROOT: /opt/android/sdk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ContaMetriApp
        path: bin/*
